### ISSUE TITLE
probably evil normal state overrides its key bindings

### ISSUE THREAD

**Issue by autosquid** [tuhdo/semantic-refactor#12]
![image](https://cloud.githubusercontent.com/assets/758925/8122732/088de3e8-10f1-11e5-8501-e17e5f1db969.png)

1. in mini-buffer, moving to 2, and press 2 works as expected
2. in mini-buffer, moving to 1, and press 2 works as if 1 is pressed.

**Comment by tuhdo** [comment]
So, I fixed this issue by enabling `evil-emacs-state`, so the default key bindings can work normally. You can use Emacs state, since `j` and `k` is supported in the state already.

A bit late but better than none. Thank for reporting. Now Refactor is also much faster. That is, instead of parsing everything included and block Emacs, now it truly works locally for local operations.
