### ISSUE TITLE
Add customization for "Generate Function Implementation"

### ISSUE THREAD

**Issue by andyque** [tuhdo/semantic-refactor#6]
Currently the "Generate Function Implementation" feature always generate a function with the following style:

```
void foo(int bar){
}
```

But in our project, we are using this style:

```
void foo(int bar)
{
}
```

I haven't found any customization in srefactor,  how could I hack this behavior?

Thanks for providing this awesome package. :)

**Comment by tuhdo** [comment]
I intended to add styles to generated code at first since it is easy to do when we have access to an abstract syntax tree. But then I thought that it would be trivial to use Emacs's editing capacity to change it i.e. you can use a macro to change the generated code, so other features have higher priority. You may also consider using [astyle](http://astyle.sourceforge.net/astyle.html) and its [Emacs integration](http://astyle.sourceforge.net/scripts.html) if it works for you.

**Comment by tuhdo** [comment]
> Thanks for providing this awesome package. :)

Thanks :)

**Comment by andyque** [comment]
@tuhdo 
Thanks, I will try *astyle*.
